### ISSUE TITLE
您好，请问您的该文件应该如何使用呢？

### ISSUE THREAD

**Issue by lzkgbld** [spencer404/v2ray-api#5]
我尽可能从您提供的信息获取帮助，但是还是感觉比较迷惑，您所说的使用是否是新建一个py文件，在里面填写相关信息后进行调用，还是什么意思？而且我注意到您的项目似乎是支持ubuntu或者centos？应该就是Linux系统，如果我想先在Windows上进行测试，我应该进行哪方面的修改？
期待您的回复，可能会打扰到您。

**Comment by lzkgbld** [comment]
我尝试在centos上安装了环境进行使用，但是依旧报错：
Traceback (most recent call last):
  File "Demo.py", line 2, in <module>
    from client import Client, VMessInbound
  File "/home/v2ray-api/client.py", line 6, in <module>
    from .errors import *
ImportError: attempted relative import with no known parent package

**Comment by lzkgbld** [comment]
我尽量尝试修复最后还是报错：
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "Trying to connect an http1.x server"
	debug_error_string = "{"created":"@1595085656.462000000","description":"Error received from peer ipv4:119.39.28.9:20020","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Trying to connect an http1.x server","grpc_status":12}"
>

**Comment by speng4096** [comment]
是不是v2ray服务器没开，或者没打开V2Ray的HandlerService
